# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Directories
tag_dir: tags
archive_dir: archives
category_dir: categories

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: images/richard.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Richard
        author_title: Thinking, coding and writing. Giving, loving and sharing.
        location: Hangzhou, China
        follow: https://github.com/hsuehic/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/hsuehic
        twitter: /
        facebook: /
        dribbble: /
        rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: true # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: hexo-theme-icarus # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-89449051-1 # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 6ce1aebf3910c970f3ed8db2f18359e1 # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Vue-kit: http://vue-kit.gismall.com/#!/dashboard
        Vue-kit mobile: http://vue-kit.gismall.com/mobile.html#!/index
        Hexo: http://hexo.io
        ATUI: http://atui.alibaba.net

